name: creusot
base: core24
version: '0.1'
summary: Snap for the Creusot formal verifier
description: |
  Formally verify Rust code with Creusot.

grade: devel
confinement: classic

apps:
  cargo-creusot:
    command: bin/cargo-creusot
    environment:
      PATH: $SNAP/bin:$PATH


parts:
  creusot-and-provers:
    plugin: rust
    source: https://github.com/creusot-rs/creusot.git
    source-type: git
    build-packages:
      - unzip
      - curl
      - make
      - gcc
      - m4
      - pkg-config
      - libgmp-dev
      - patch
    override-build: |
      export OPAMROOT=$CRAFT_PART_INSTALL/opam
      export OPAM_DISABLE_SANDBOXING=1
      export OPAMROOTISOK=1
      export OPAMYES=1

      export OPAMCONFIRMLEVEL=unsafe-yes
      export DEBIAN_FRONTEND=noninteractive

      echo "Fetching upstream opam binary..."
      curl -L "https://github.com/ocaml/opam/releases/download/2.2.1/opam-2.2.1-x86_64-linux" -o /usr/local/bin/opam
      chmod +x /usr/local/bin/opam

      echo "Initializing Opam..."
      opam init default https://opam.ocaml.org --disable-sandboxing

      echo "Creating OCaml 5.3.0 switch..."
      opam switch create 5.3.0
      eval $(opam env)

      echo "Installing Creusot dependencies..."
      opam install . --deps-only -y

      mkdir -p $CRAFT_PART_INSTALL/bin
      cp $OPAMROOT/5.3.0/bin/why3* $CRAFT_PART_INSTALL/bin/

      rustup default stable
      craftctl default

      cp target/release/cargo-creusot $CRAFT_PART_INSTALL/bin/
      cp target/release/creusot-rustc $CRAFT_PART_INSTALL/bin/

      echo "Downloading Z3..."
      curl -L "https://github.com/Z3Prover/z3/releases/download/z3-4.15.3/z3-4.15.3-x64-glibc-2.39.zip" -o z3.zip
      unzip z3.zip -d z3_ext
      cp z3_ext/*/bin/z3 $CRAFT_PART_INSTALL/bin/

      echo "Downloading CVC5..."
      curl -L "https://github.com/cvc5/cvc5/releases/download/cvc5-1.3.1/cvc5-Linux-x86_64-static-gpl.zip" -o cvc5.zip
      unzip cvc5.zip -d cvc5_ext
      cp cvc5_ext/*/bin/cvc5 $CRAFT_PART_INSTALL/bin/

      echo "Downloading CVC4..."
      curl -L "https://github.com/CVC4/CVC4-archived/releases/download/1.8/cvc4-1.8-x86_64-linux-opt" -o $CRAFT_PART_INSTALL/bin/cvc4
      chmod +x $CRAFT_PART_INSTALL/bin/cvc4

      echo "Downloading AltErgo..."
      curl -L "https://github.com/OCamlPro/alt-ergo/releases/download/v2.6.2/alt-ergo-v2.6.2-x86_64-linux-musl" -o $CRAFT_PART_INSTALL/bin/altergo
      chmod +x $CRAFT_PART_INSTALL/bin/altergo

      rm -rf target/

      rm -rf $OPAMROOT/download-cache
      rm -rf $OPAMROOT/repo/default/archives/*

      rm -f z3.zip cvc5.zip
